title: Griiid
description: Hi, welcome to Griiid's blog!

url: https://griiid.github.io
baseurl: ""
imgurl: "/assets/img"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
#  - title: Contact
#    url: /contact

social:
   github: griiid
   facebook: annheilong
   email: gridwing@gmail.com
#  twitter: brianmaierjr

google_analytics: "UA-108611085-1"
