title: Griiid
description: Hi, welcome to Griiid's blog!
author: Griiid
copyright: Griiid
keywords: Griiid, Griiider, 方格子, 許晉豪, C, C++, Objective-C, Swift, iOS, app, git, Mac, OSX

url: https://griiid.github.io
baseurl: ""
imgurl: "/assets/img"
paginate_path: "blog/page:num/"
permalink: blog/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
#  - title: Contact
#    url: /contact

social:
   github: griiid
   facebook: annheilong
   email: gridwing@gmail.com
#  twitter: brianmaierjr

google_analytics: "UA-108611085-1"

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

kramdown:
  hard_wrap: false