title: Griiid
description: Hi, welcome to Griiid's blog!

url: ""
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
#  - title: Contact
#    url: /contact

social:
   github: griiid
  #  twitter: brianmaierjr
   facebook: annheilong
   email: gridwing@gmail.com

# google_analytics: "UA-58263416-1"
